# Generated by Django 4.0.6 on 2022-07-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
